### ISSUE TITLE
Add uitable just below the streachable view and then work same as it working now.

### ISSUE THREAD

**Issue by sandy99** [ericcastro/ECStretchableHeaderView#3]
I tried to add UItableview just under the neath of streachableview but getting issue with tableview , it's shows extra space , orange color in attached image.
![screen recording](https://cloud.githubusercontent.com/assets/1879847/9385166/881f2d26-4772-11e5-9777-5097cddee73a.gif)

and also headerview is not moviing with Tableview. you can rename git to mov, it's video file.

<img width="423" alt="screen shot 2015-08-20 at 7 30 15 pm" src="https://cloud.githubusercontent.com/assets/1879847/9385123/4d6d1c74-4772-11e5-9eef-1b6015eba90c.png">

**Comment by ericcastro** [comment]
Hi Sandeep,

Can you please post the source code you're using?

Have you tried the example project and maybe try copying/pasting and start from there?

**Comment by sandy99** [comment]
Source code : https://www.dropbox.com/s/fn0rr3masvitr37/AdujstableHeaderView.zip?dl=0

What i want to implement.
Step 1: TableView should be under neath of StreachableView.
Step 2: When User Scroll up tableView streachableview should be shrink by 300 px to 100 px(max = 300 & min =100) and tabelview also just under the neath.
there are some header also inside plan tableview. 
Step 3: Again when user scroll Down then Streachable view show with actual position by 300.

**Comment by ericcastro** [comment]
Hi Sandeep,

Your problem was mainly in your Storyboard layout. The TableView is not supposed to be connected to the header view with a top space constraint. The header view must be ON TOP on it instead, and the table view must be constrained to its containing view.

Also, there is a sample image that is supposed to be in the header view, so put it there instead of the containing view . Anything that is part of the header view must be a child of the header view.

I fixed your layout to get the desired effect. Download it from here:
http://dropcanvas.com/#r72w58u3J9GfR5

**Comment by sandy99** [comment]
Thank you so much Eric.

**Comment by sandy99** [comment]
Eric you added UITabelview from very top ..
Can i add it under neath of overlayview and update the uitableView offset and inset.

**Comment by ericcastro** [comment]
Can you please elaborate on your last question ?

You can start by explaining what is the problem and what do you want to achieve.

Next, try it yourself, and if you have a problem then let me know.

Finally, start from the project I gave you, which is the correct implementation of this control.
